version: '3'

services:
  frontend:
      image: kurkkumopofront
      build: ./ml-kurkkumopo-frontend
      ports:
        - 3000:3000
  backend:
      image: kurkkumopobackend
      build: ./ml-kurkkumopo-backend
      ports:
        - 5000:5000
      volumes:
        - model:/src/model
      depends_on:
        - training
  training:
      image: kurkkumopotraining
      build: ./ml-kurkkumopo-training
      volumes:
        - imgs:/src/imgs
        - data:/src/data
        - model:/src/model

volumes:
  imgs:
  data:
  model:
