version: '3'

services:
  backend:
      image: backendexample
      build: ../../part1/exercise_1.11
      ports:
        - 8000:8000
      environment:
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
        - REDIS_PORT=6379
        - DB_USERNAME=postgres
        - DB_PASSWORD=password
        - DB_HOST=db
      depends_on:
        - db
  frontend:
      image: frontendexample
      build: ../../part1/exercise_1.10
      ports:
        - 5000:5000
      environment:
        - API_URL=http://localhost:8000
  redis:
      image: redis
      ports:
        - 6379:6379
  db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres

